@baseUrl = http://localhost:3000

### 🏠 Home Controller
# @name AppControllerGetHello
GET {{baseUrl}}/home


###  Concepts Manual
# @name ConceptsManualController
GET {{baseUrl}}/concepts-manual


###  Concepts Automatic
# @name ConceptsAutomaticController
GET {{baseUrl}}/concepts-automatic


### 💬 Messages Controller

#  Get all messages
GET {{baseUrl}}/messages

#  Get one message
GET {{baseUrl}}/messages/1/

#  Create new message
POST {{baseUrl}}/messages/
Content-Type: application/json

{
  "message": "Message.."
}








